import { Rating } from './Rating';

export const RATINGS_UNALIGNED: Rating[] = [
    { review: 'I bought 2 of the unaligned skirts, I love the look with the angled front and rear seams; that feature changes the way the skirt hangs and moves and adds individuality to the design. The skirts arrived well packed in environmentally friendly envelopes filled with shredded recycled paper, potentially messy but not an issue if the envelopes are opened as intended. The skirts had been folded together with no tight bends to cause creasing so they were wearable straight out of the bag, or would have been had it not been for the instruction to wash and dry them before use (to finish shrinking to size). Both skirts did shrink slightly, as they should, but I would have preferred it had they shrunk a little more. The skirts have proved to be comfortable, if slightly generous in the waist measurement (an inch or so larger than the nominal size). However, the inclusion of plenty of belt loops means this is not a problem and the asymmetry of the design lends itself to an off-centre belt buckle, adding another nice visual difference to the skirts. In use, the top pockets have proved to be well positioned and sized and the two lower pockets are cavernous, almost too large when I\'m trying to get my phone before it stops ringing. The skirts are completely unrestrictive, allowing a full stride, even for me at 6\' 3\" tall, and the fabric weight means the skirt does not flap excessively in strong winds. The construction is first rate. I could not find a single loose or off-cut of thread nor untrapped end on either skirt and every stitch line runs straight & true with a perfectly even stitch length; something I cannot say about many clothes these days. Detailing is good with a neat logoed button and tidily integrated lower pockets. Pressing the skirt revealed that the upper pocket panels are a bit fiddly, but that is not a significant issue. The only thing stopping me buying a third skirt is that I\'ve run out of colours! How about making the skirt available in olive green?', name: 'Ian, Buckinghamshire, England', ratingStars: 5, date: '2015-12-07 00:00:00' },
    { review: 'I love my skirt and I\'m glad to have supported this effort towards inclusive clothing!', name: 'Robert-Carnilius, Chicago', ratingStars: 5, date: '2015-12-07 01:00:00' },
    { review: 'Out side of the tag that does not say made for men,I like the looks of the skirt,good heavy fabric,nice stitches,big deep pockets,crooked zipper is cool and belt loops,above all nice skirt.', name: 'Larry, Orange, California', ratingStars: 5, date: '2015-12-07 01:30:00' },
    { review: 'Very happy with this skirt. It is wonderful and I hope that its existence makes the world a more free and happy place for others as it opens the possibility for menswear beyond the boring classic non-evolving options that for the most part dominate the men\'s clothing landscape.', name: 'Derek, Toronto', ratingStars: 5, date: '2015-12-07 02:00:00' },
    { review: 'the best ! Excellent, finally a skirt for men. Long life to the unaligned skirt !', name: 'Rémi, Lyon, France', ratingStars: 5, date: '2015-12-08 02:00:00' },
    { review: 'Finally!! A skirt I can wear anywhere that is actually a \"man\'s\" skirt and not something bought from the women\'s department. Let that clothing wall fall down!', name: 'Jkilter', ratingStars: 5, date: '2015-12-08 05:00:00' },
    { review: 'great skirt. Keep up the good work Joe.', name: 'Buddy, NC', ratingStars: 5, date: '2015-12-08 08:00:00' },
    { name: 'Matthew', ratingStars: 4, date: '2015-12-08 09:00:00' },
    { review: 'I\'m very pleased with the Unaligned Skirt, delighted with the customer service and excited to see what other products come from Skirtcraft! Even if the skirt had not been exactly what I was looking for, the excellent service would have won me over. I can\'t say enough about how important that is - it often seems like a lost art, but it\'s in full force at Skirtcraft, with Joe leading the way. The actual skirt is even better than I was anticipating. The fit was just right for me, even after washing and drying (I always wash my cottons in cold and air dry the first two or three times before I wear it). It does get softer after washing - another plus. And I love the way it looks! Thanks.', name: 'Todd, Fairfield', ratingStars: 5, date: '2015-12-08 10:00:00' },
    { review: 'An excellent product for the first production run! Sleek and modern design with a sturdy feel, definitely suitable for all men and women! The denim chosen has just the right weight and the drape starts to fall nicely after the first wash. Furthermore, the denim softness hits the right spot, it is sturdy and relaxed for men, yet soft and strong for women. This has to be the best way to describe it. And with great functionality too! The best and most versatile skirt ever seen!', ratingStars: 4, date: '2015-12-08 10:30:00' },
    { review: 'The design of the skirt is fantastic. Not only is it really attractive, it is also extremely practical and the workmanship is beautiful. And those features are on top of the fact that it is an ungendered skirt! Finally, the customer service has also been first-rate. This really has been an excellent purchase.', name: 'Anonymous, New Zealand', ratingStars: 5, date: '2015-12-08 16:00:00' },
    { review: 'Guys, we\'ve been lied to since childhood. Skirts are NOT just for girls. I can\'t believe how free my legs feel. I love these skirts from Skirtcraft!', name: 'Andrew, Ontario, Canada', ratingStars: 5, date: '2015-12-08 17:00:00' },
    { review: 'Absolutely love the skirt! Well built and worth the price. The \"A\" frame shape works well with a masculine body shape and the pockets rock. I Have a US made kilt as well and much prefer this skirt for comfort, look, and shape.  ', name: 'Kelly, Caik, SK / Riverstone Studios', ratingStars: 5, date: '2015-12-09 00:53:01' },
    { review: 'nice skirt, pockets, shape, i ordered another skirt different color and next size smaller, the first is a little big after washing, still fits i need to wear a belt but thats ok !!!', name: 'Charlie, K Falls', ratingStars: 5, date: '2015-12-10 00:00:00' },
    { review: 'It is an excellent quality garment for a reasonable price compared to other man-skirts such as original Utilitikilts. It is very comfortable, allows a full stride (I have long legs) with no feeling of restrictiveness. Very pleased with it ', name: 'Ross, Edinburgh, UK', ratingStars: 5, date: '2015-12-11 06:37:23' },
    { review: 'The unaligned skirt is the kind of fashion twist that men need and just the kind of utility that a women would want in an every day skirt. Gender is defined by self, not by clothes. Keep up the well-crafted work Skirtcraft.', name: 'Ryan, California', ratingStars: 5, date: '2015-12-12 04:47:06' },
    { review: 'I am extremely impressed with the quality and the fit of this skirt. The zippers are heavy duty, and that includes the two nylon zippers. I love the multiple big pockets that provide more than ample space to carry everything I need to carry comfortably. My little .38 revolver fits perfectly and conceals itself nicely in one of the pockets. I will likely buy the other color in the near future.', name: 'Dave, Kansas', ratingStars: 5, date: '2015-12-12 07:00:00' },
    { review: 'I look fantastic in it! For a while, I was looking for original ways to improve my style and the unisex skirt has hit the spot. They match very well with my previous clothing but the overall look is greatly different. Actually, my friends have positively commented that now I look far more hipsterish. Thus, I would recommend the skirt to anybody who wants to feel original. I strongly believe that skirts are going to become the new fashion in a few years, so better not lose the opportunity to ride the wave just when it starts!', name: 'Josep, London', ratingStars: 5, date: '2015-12-12 11:00:00' },
    { review: 'Thanks for such a thoughtful design and amazing execution! I found that your sizing is really quite excellent. I am looking forward to your next offering to be introduced.', name: 'Matt in Washington', ratingStars: 5, date: '2015-12-13 14:05:00' },
    { review: 'Really happy with the skirt -although I have plenty of skirt choices, it\'s hard to find women\'s skirts this sturdy and with POCKETS! ', name: 'Pittsburgh, PA', ratingStars: 4, date: '2015-12-16 03:23:55' },
    { review: 'Love this skirt. Cute with leggings and boots. Excited to wear it with sandals this summer. Pockets actually hold things and do not bulge.  Fits nice just below my bellybutton.', name: 'Sarah, Minneapolis', ratingStars: 5, date: '2015-12-17 04:32:56' },
    { review: 'Good product, feels good to wear. Feels at waist just like pants.', name: 'Smuggins, Minneapolis', ratingStars: 5, date: '2015-12-23 21:26:59' },
    { name: 'Alain, France', ratingStars: 4, date: '2015-12-27 03:05:06' },
    { review: 'For a while I was asking myself why men are not wearing skirts when the Kickstarter project of Joe crossed my path. I immediately sustained the project. After shipping problems I finally received my skirt.  The quality is very good and it does look like something wearable for men. Comparing it with wearing my jeans, it is surprisingly comfortable and ergonomic. It does not have the tendency to sink down how simple it is to put your hands in the pockets!  The next step is outside... Chile is a super macho country, so I was warned to engage vocal, or even physical, encounters. At least my wife, who was skeptical, was enthusiastic about the look of it and assured me she doesn\'t have a problem walking next to me. The first comment was from a heavy metal loving young nephew: a skirt! Wow... Cool! After Xmas dinner with my family we discussed a little about \"why not?\" and all excepted.  Yesterday I came out of the car... and entered the local mall to go the supermarket, hand in hand with my wife. While everybody was looking at me I was looking at everybody. I don\'t think that I got more looks than what is normal because of a red beard, being milky white, wearing a tshirt with an \"Eco text\". And while looking myself I discovered that many fellow men or, even, women are looking at least as ridiculous I would. Or not at all! Later my wife told me that various people have been staring, but nobody made a \"not accepting grim\". My first day in public didn\'t bring any trouble, but surely I will get negative comments. And, while it is high summer here, my first day learned me as well that a skirt is a welcome ventilating piece of clothing.  The only things I never thought of: how to sit with a skirt on, how to stand up from the couch or how to step in and out of the car! My first day in public brings me back to my original question, but with a different meaning: why aren\'t men wearing skirts? Good idea Joe! I hope that more people will accept the skirt as a unisex garment.', name: 'Harry, Chile', ratingStars: 5, date: '2015-12-27 13:23:46' },
    { review: 'Pluses: This is a comfortable and sturdy-feeling skirt. I love having the deep pockets! It washes well in cold water, machine dry low. The color is a good dark black. It is good for casual wear or wear to work (my workplace is fairly casual). There are lots of belt loops where you can clip your keys or whatever.  Drawbacks: This skirt does show lint/pet hair easily. Use a sticky roller. The A-line shape does not fit perfectly over my curves. That\'s fine for me, but know that if you are curvy with large hips and slim waist, it will not lie smoothly on you.', name: 'Female, 45, Portland OR', ratingStars: 4, date: '2015-12-28 14:00:00' },
    { review: 'Absolutely thrilled with how the skirt arrived, its quality, and how comfortable it is. Thanks to all involved.', name: 'Aaron, ACT, Australia', ratingStars: 5, date: '2015-12-28 16:00:00' },
    { review: 'Excellent skirt. Wish it would be more accepted in the streets :)', name: 'Robert, the Netherlands', ratingStars: 5, date: '2015-12-29 02:00:00' },
    { review: 'Amazing skirts!   The material and craftsmanship is top notch.   All of the zippers work so easily. I have one of each color and I have washed them twice so far and the khaki shrank a little more than the black.  I have debated having one of them shortened.  I prefer a 20 inch length on a skirt.  But on these a 22.5\" length gives you just a little more coverage when sitting. So I am torn. The longer and fuller skirt is so comfortable but I don\'t like the look of it on me.  But for now they are staying long.  Keep up the good work.  I hope in the future we will see more unisex skirt designs come out.', name: 'Rich - PA', ratingStars: 5, date: '2016-01-19 04:32:18' },
    { review: 'Excellent build. Great comfort and fit. Exactly what I was looking for in a market that is flooded with modern kilts.', ratingStars: 5, date: '2016-01-24 04:59:13' },
    { review: 'As a male in late 20th century western civilization, I had no skirted options in my closet for most of my life. At an early age, a series of incidents caused me to learn to be extremely careful while zipping up my pants. I also became acclimated to the need to frequently \"adjust myself\" and, like most boys and men, not to even notice when I do it...or how frequently. At a certain point I just accepted that the sudden, sharp pains in the groin area due fabric binding against sensitive body parts that happen to be susceptible to just that were just an unavoidable reality. Long hours either driving or sitting at a desk in an office reveal the sinister twin problem: the dull, aching numbness that happens when the fabric binds you but you don\'t notice because it didn\'t cause the aforementioned sharp pain. You then hit middle age, and your doctor tells you that unless you can get some more ventilation down there, your risk of cancer and other issues increases. He suggests boxer shorts, but in practice, that just causes more cloth being stuffed into the same limited space and only makes things worse.  Then the aliens came. They laughed at me and called me stupid. They said that given human anatomy, men wearing pants and women wearing skirts was exactly backwards and until we wised up, there\'d be no joining the Planetary Federation for us...and that the invasive probing would continue.  Skirtcraft changed my life. I can sit at my desk for hours now and never be bothered by debilitating groin pain. And the comfort! Captain Malcolm Reynolds had it right, there\'s a whole airflow thing...particularly nice on a hot summer day. Alien encounters now happen in coffee shops over a nice double shot mocha rather than in sterile rooms equipped with cold, stainless steel equipment.  In short, my life is now rather awesome. Thank you, Skirtcraft! Definitely a five star company, if you ask me. And you did. Aren\'t you glad?', name: 'LRS, Central Virginia, USA', ratingStars: 5, date: '2016-02-08 05:17:25' },
    { name: 'Biker JIM', ratingStars: 5, date: '2016-02-17 05:09:23' },
    { name: 'Deedee', ratingStars: 3, date: '2016-02-28 04:26:11' },
    { name: 'Victor in Melbourne, Australia', ratingStars: 5, date: '2016-02-28 04:26:42' },
    { review: 'Excellent, enfin une jupe Homme faite pour les hommes. Quel bonheur, quel confort. Obligatoire.', name: 'Rémi, France', ratingStars: 5, date: '2016-04-07 15:11:28' },
    { ratingStars: 5, date: '2016-04-18 17:23:38' },
    { ratingStars: 5, date: '2016-05-17 14:12:48' },
    { ratingStars: 5, date: '2016-05-18 13:16:05' },
    { ratingStars: 5, date: '2016-06-21 05:18:18' },
    { ratingStars: 5, date: '2016-06-22 05:18:48' },
    { ratingStars: 5, date: '2016-06-22 10:19:23' },
    { review: 'Order wrong size and exchanging for correct size was easy and company was very helpful. Skirt is extremely comfortable and love the large pockets. Hope you can come out with a longer length for a second choice at some point.  Keep up the good work. ', name: 'Anonymous / Northern Indiana, USA', ratingStars: 5, date: '2016-06-22 19:53:07' },
    { review: 'Finally I found a skirt made for a man and intend to rock it!!!', name: 'Jesse', ratingStars: 5, date: '2016-06-23 05:19:49' },
    { name: 'JC in northern Indiana', ratingStars: 4, date: '2016-06-23 05:20:07' },
    { review: 'Skirt is awesome, soft yet durable material. I like the pockets. Perfect for my man-skirt Mondays or any day. Looking forward to see what else you guys come up with. Maybe a larger colour palate? (including pink) or a longer winter skirt? Maybe a lighter material for the beach? Keep rocking it and follow your dreams.', name: 'Dale, Ontario Canada', ratingStars: 5, date: '2016-06-24 16:18:30' },
    { ratingStars: 5, date: '2016-06-25 02:19:31' },
    { review: 'I wear a kilt from time to time , and I really can\'t understand  why it\'s taboo for men to wear  skirts . I love my  black Skirtcraft skirt , well made and comfortable , and am ordering a khaki one . It\'s a lot like a kilt , but without the pleats and apron . And the pockets are killer . Did I mention it\'s very comfortable with no pinching or binding in the privates ! I don\'t mean to offend anyone by wearing my skirt , but I feel its a bonus . I Hope a long skirt , say 38\" or so is in the works , I\'ll be first in line to buy it . Thanks', name: 'Frank Moore', ratingStars: 5, date: '2016-07-24 03:27:48' },
    { review: 'The garment has stopped the testicular irritation  getting from when I was wearing pants or shorts from those blasted seam which are usually in that area, Thanks, the skirt is great.', name: 'Sydney, Australia', ratingStars: 5, date: '2016-09-05 06:53:00' },
    { review: 'After buying this garment I have been able to do away with bum bag or fanny pack.', name: 'Australia', ratingStars: 5, date: '2016-09-06 09:19:00' },
    { ratingStars: 5, date: '2016-09-21 01:13:37' },
    { review: 'I\'m very pleased with the skirt having been the first \"skirt\" I ever bought for myself and openly wore around. Sure my dozen of kilts are essentially the same thing, but they are still different enough in the eyes of other people. I\'m happy to have bought it, and glad to wear it around town.', name: 'Alan in Colorado', ratingStars: 4, date: '2016-09-22 02:15:19' },
    { ratingStars: 5, date: '2016-09-22 17:18:04' },
    { review: 'A nicely made product with much attention to detail. Professionally made and likely to give satisfaction.', name: 'Al', ratingStars: 4, date: '2016-09-23 17:18:50' },
    { review: 'Great product. Seems to stand up to every day wear - get good complements on it. 5 stars if the bottom pocket contents didn\'t end up under my legs when I sit. But I can\'t complain too much.', name: 'Dale - Ontario', ratingStars: 4, date: '2016-09-26 17:19:41' },
    { ratingStars: 5, date: '2016-10-09 03:45:39' },
    { review: 'I wore my khaki skirt to the White House! Husband planned a surprise visit while on vacation, and you cannot take any bags or backpacks there. Happily I had deep pockets and could survive without my purse.  Love both my skirts (I\'m a Kickstarter backer), they are tough, comfy, and have belt loops for my work security card. I\'ve been wearing them weekly for months now with no signs of wear.', name: 'A Hawke, Missouri', ratingStars: 5, date: '2016-10-11 12:03:07' },
    { review: 'Better quality than the sweatshop stuff you get on from high street stores.', name: 'Martin Barr-David, Sydney, Australia', ratingStars: 5, date: '2016-10-14 02:22:28' },
    { review: 'If you\'re looking for a skirt, look no further. It\'s here!', name: 'Werequat', ratingStars: 5, date: '2016-11-29 13:18:51' },
    { ratingStars: 4, date: '2016-11-29 15:19:22' },
    { review: 'This is the first product I have seen that is designed for a mans body. The best fit I have had.', name: 'BJ in Florida', ratingStars: 5, date: '2016-11-29 16:20:02' },
    { ratingStars: 4, date: '2016-11-29 18:20:23' },
    { ratingStars: 5, date: '2016-11-29 19:20:53' },
    { name: 'Will', ratingStars: 5, date: '2016-11-29 20:21:14' },
    { review: 'I\'m a big fan of this company and this lovely skirt!', name: 'John in Minneapolis', ratingStars: 5, date: '2016-11-29 23:18:16' },
    { ratingStars: 5, date: '2016-11-30 00:00:00' },
    { review: 'I haven\'t gotten one of these skirts yet, but these look good!  I definitely want to get one soon!  I hope your business is doing good!', name: 'Matthew', ratingStars: 5, date: '2017-01-02 21:28:49' },
    { review: 'Your skirts rock.  I have one black and one khaki.  Your customer service is over the top excellent as well.    When other people see you out in your skirt they will have permission to do the same, then men in skirts won\'t be thought of as a peculiarity.  ', name: 'Matt in Yakima', ratingStars: 5, date: '2017-02-01 23:24:57' },
    { ratingStars: 5, date: '2017-02-02 03:49:25' },
    { ratingStars: 5, date: '2017-02-02 04:49:53' },
    { review: 'I found the skirt very comfortable to wear, sizing issue isn\'t too much of a problem, I solved that by wearing a belt with it, however it would be nice if there was a lighter fabric for summer and maybe some more colours, like reds, blues, purples, greys, greens and so on.', name: 'Mark W, Brisbane, Australia.', ratingStars: 4, date: '2017-02-02 06:52:05' },
    { review: 'Skirts is great, and quite easy to wear out in public. You just have to \'own\' it and not be afraid. Comfort is fantastic.', ratingStars: 5, date: '2017-02-02 09:52:40' },
    { ratingStars: 3, date: '2017-02-08 03:53:12' },
    { review: 'I really like these skirts will order one as soon as I have the money saved up.I love the feel of a skirt with the freedom of movement.Also they are a cooler garment to wear than pants especially made of denim. Thank for your clothing design. Sincerely terry ', name: 'terry luscher Berlin Wi.', ratingStars: 5, date: '2017-03-02 13:46:22' },
    { ratingStars: 5, date: '2017-06-21 15:20:58' },
    { ratingStars: 5, date: '2017-06-21 15:21:41' },
    { ratingStars: 3, date: '2017-06-21 15:22:09' },
    { ratingStars: 5, date: '2017-06-21 15:24:39' },
    { ratingStars: 5, date: '2017-06-21 15:25:16' },
    { ratingStars: 5, date: '2017-06-21 15:27:53' },
    { ratingStars: 5, date: '2017-06-21 15:28:25' },
    { review: 'Made for all and enjoyed by me.', ratingStars: 5, date: '2017-06-21 15:28:45' },
    { review: 'Thank you skirt craft for continuing breaking barriers about skirts for men.. and of course women..As time goes on the style of a more and more accepted. You\'re doing a great job keep pushing out more styles love skirts I\'m a guy who owns over 25 kilts.', name: 'Tommy in Hoboken NJ', ratingStars: 5, date: '2017-06-21 15:29:00' },
    { ratingStars: 4, date: '2017-06-21 15:29:21' },
    { review: 'Love the idea of skirts for all. The pockets are amazing especially the ones with zippers. keep up the great work.', name: 'Mark in New Orleans', ratingStars: 4, date: '2017-06-22 03:58:38' },
    { ratingStars: 4, date: '2017-06-27 14:20:25' },
    { review: 'This skirt is amazing. It fits very well. I could wear it every day! If there were more colors I would order one of every color and then I would have one for every day!', name: 'DJ', ratingStars: 5, date: '2017-07-16 14:17:30' },
    { review: 'Very well made product, very comfortable to wear.', name: 'RL', ratingStars: 5, date: '2017-07-16 14:17:53' },
    { ratingStars: 5, date: '2017-07-17 14:37:51' },
    { review: 'I wear kilts often 2 to 3 days a week .. and to my office in NJ .. I must say this is a very cool design.. I have your  Black and Tan Skirts .. Yes I wear them to the office too Great Job .. More Colors a Plus..', name: 'Thomas', ratingStars: 5, date: '2017-08-04 03:14:14' },
    { ratingStars: 4, date: '2017-08-30 00:52:59' },
    { review: 'I have two black unaligneds, and two tan unaligneds.  Love em.  Waiting to order the new model as well.  Would LOVE a dressier-looking model, perhaps in lined wool, to be more office-appropriate.  Thinking of something like Celtic Thunder wear on stage. Cheers.  Matt', name: 'Matt, Washington', ratingStars: 5, date: '2017-08-30 17:58:53' },
    { review: 'I absolutely love my unaligned skirt.  My wife loves it too and wants one so we can match.  Thank you so much!', name: 'Portland, TN', ratingStars: 5, date: '2017-09-30 07:45:02' },
    { review: 'It has excellent pockets and actual belt loops', name: 'Garayur', ratingStars: 5, date: '2017-10-16 02:38:01' },
    { review: 'I love this shirt. The fabric is great -- soft and rugged. The design is practical and yet interesting -- pretty and functional.   My preferred size was not available, so I got a size up. I made a pleat in the front to make it fit. The skirt doesn\'t fall exactly as it should, but it still looks and feels awesome. I look forward to getting another one in my proper size. Love it!', name: 'Clover in Toronto', ratingStars: 5, date: '2017-10-17 20:36:29' },
    { ratingStars: 4, date: '2017-11-15 03:10:22' },
    { ratingStars: 5, date: '2017-11-15 03:11:00' },
    { ratingStars: 5, date: '2017-11-15 03:11:34' },
    { ratingStars: 3, date: '2017-11-16 03:12:52' },
    { ratingStars: 5, date: '2017-11-18 02:47:18' },
    { review: 'I love the skirt so much, i could wear it every day. I have kilts and love to wear them too. Even some skirts that i find under the ladies department i love to wear.  I own the black one, and ordered a khaki color too.', name: 'Marco , Woubrugge NL', ratingStars: 5, date: '2017-11-25 07:20:07' },
    { ratingStars: 4, date: '2017-11-26 03:27:47' },
    { review: 'When my first purchase didn\'t fit as I would like Skirtcraft was great about an exchange for a different size.', name: 'FtonDavid', ratingStars: 5, date: '2018-04-23 04:46:18' },
    { ratingStars: 4, date: '2018-04-23 04:46:46' },
    { name: 'Marco in the Netherlands', ratingStars: 5, date: '2018-04-23 04:47:04' },
    { review: 'I found out about this company before their products went on sale and I am so thankful they do what they do. As soon as I discovered their skirts were available, I ordered one without a second thought. Skirts are not just for women. They are for everyone. I\'m happy that there is a company out there making a difference in men\'s fashion and challenging arbitrary social norms. I hope other companies learn from Skirtcraft that men can rock skirts too.', ratingStars: 5, date: '2018-04-23 04:47:42' },
    { name: 'John', ratingStars: 5, date: '2018-04-23 04:47:58' },
    { ratingStars: 5, date: '2018-05-02 02:40:04' },
    { review: 'Be careful with the sizing. I followed the directions explicitly, but the skirt was way too big in the waist. I can\'t wear it. Great quality and design though.', name: 'Tom in Boston', ratingStars: 3, date: '2018-05-13 04:49:54' },
    { review: 'Still wearing the skirts almost every day. They stay beautiful after a lot of washing since I bought the skirts 7 months ago.', name: 'Marco, Woubrugge,  Netherlands', ratingStars: 5, date: '2018-05-22 06:44:19' },
    { review: 'Received my skirt this week, it\'s great! It fits me perfectly, and, despite the material being thick, it\'s very good for this hot weather (30 C and more) because good air flow.', name: 'Andrej, Slovakia', ratingStars: 5, date: '2018-07-28 21:22:51' },
    { ratingStars: 4, date: '2018-08-17 16:15:18' },
    { ratingStars: 5, date: '2018-08-17 16:19:51' },
    { ratingStars: 5, date: '2018-08-17 16:21:19' },
    { review: 'Nice and original product .Very fast delivery , well packaged !', name: 'Franck in Paris', ratingStars: 5, date: '2018-08-17 16:22:13' },
    { review: 'Skirts are for everyone to wear. Not just women! There\'s no reason why one kind of clothing should be exclusive to one gender. Guys, do yourself a favor and order a skirt from this site and rock it with confidence. They look great, they\'re very comfortable, and keep you a lot cooler than shorts in this hot weather.', name: 'Toll in PA', ratingStars: 5, date: '2018-08-17 16:23:50' },
    { review: 'This product is very unique conceptually in its design, durability, and practicality. The \"Skirt with Pockets\" is made of high quality materials. I personally can\'t express how excited I am about it!', name: 'Marcus Hering, Minneapolis, MN', ratingStars: 5, date: '2018-08-18 16:29:29' },
    { name: 'Joa in Boulder', ratingStars: 5, date: '2018-08-18 16:32:47' },
    { name: 'George', ratingStars: 5, date: '2018-08-18 16:33:17' },
    { review: 'I like my unaligned skirt. In summertime i wear it very often.', name: 'Ralf in Germany', ratingStars: 5, date: '2018-08-24 03:45:34' },
    { name: 'Judah in Stafford', ratingStars: 5, date: '2019-03-30 23:58:34' },
    { review: 'These guys are legit. The product is solid and the service is top notch.', name: 'Robert Hancock', ratingStars: 5, date: '2019-03-30 23:59:45' },
    { ratingStars: 4, date: '2019-03-31 00:00:35' },
    { review: 'I love my skirt! It fits perfectly and I can shift it from my waist to my hips to cover my knees to keep warmer. The length is great for me! The pockets are very well thought out too. Doesn\'t affect the lines or fit when items are pocketed, even.', name: 'Eddie', ratingStars: 5, date: '2019-03-31 00:01:23' },
    { review: 'I have tried the unaligned skirt and I like the design and quality. I wear it out a lot and have received some good comments. After wearing my first one I immediately ordered a second.', name: 'Greg in TN', ratingStars: 5, date: '2019-03-31 00:02:01' },
    { review: 'Skirtcraft skirts are the absolute favorite skirts that I own. The pockets are huge and usable, they are comfortable, they look good, and the quality is top notch.', name: 'growflet', ratingStars: 5, date: '2019-03-31 00:02:29' },
    { ratingStars: 5, date: '2019-03-31 05:29:39' },
    { review: 'Wearing skirts is just fun. Thanks you Skirtcraft for expanding my wardrobe.', name: 'Geoff', ratingStars: 5, date: '2019-03-31 08:31:00' },
    { ratingStars: 4, date: '2019-04-02 05:28:30' },
    { name: 'Karl from NZ designer club', ratingStars: 4, date: '2019-04-04 05:18:21' },
    { ratingStars: 5, date: '2019-04-09 03:38:59' },
    { review: 'This product is the optimal way to begin encouraging men to wear skirts in a masculine fashion. Other skirt options for men, except kilts, tend to be culturally too feminine. This helps to move the cultural needle for men.', name: 'John in the Midwest', ratingStars: 4, date: '2019-04-20 03:39:35' },
    { ratingStars: 5, date: '2019-04-20 03:40:29' },
    { ratingStars: 5, date: '2019-06-15 03:42:02' },
    { review: 'well made skirts. double stitched where needed', name: 'mike in new hampshire', ratingStars: 5, date: '2019-06-15 03:42:46' },
    { ratingStars: 5, date: '2019-06-15 03:43:28' },
    { ratingStars: 5, date: '2019-06-16 03:45:33' },
    { review: 'Love this skirt, very comfortable fabric. Now to get others comfortable with it.', name: 'Wayne', ratingStars: 4, date: '2019-06-16 03:46:05' },
    { ratingStars: 4, date: '2019-06-16 03:46:32' },
    { ratingStars: 5, date: '2019-06-16 03:46:57' },
    { review: 'My husband (65 years old) loves his sporty & comfortable skirt! Well thought-out design with different types of pockets. Prompt customer service helped with a size-exchange. Would have probably chosen a larger size if I had realized the probability of shrinkage when dried. Thanks for your creativity, Skirtcraft!', name: 'ChillMpls', ratingStars: 5, date: '2019-06-18 03:47:53' },
    { ratingStars: 5, date: '2019-07-13 03:37:52' },
    { ratingStars: 5, date: '2019-07-30' },
    { date: '2019-08-24', ratingStars: 5 },
    { date: '2019-08-24', ratingStars: 5, review: 'Nice local craft' },
    { date: '2019-08-24', ratingStars: 4 },
    { date: '2019-08-24', ratingStars: 5 },
    { date: '2019-08-25', ratingStars: 4 },
    { date: '2019-09-06', ratingStars: 4 },
    { date: '2019-09-15', ratingStars: 5, name: 'Kelly in Orlando', review: 'Great, well thought out design and skirt to meet the needs of all who want comfort and style, regardless person. Kudos to Skirtcraft for offering other quality clothing choices besides the "normal". You don\'t know what your missing.' },
    { date: '2020-01-04', ratingStars: 5, name: 'Brent', review: 'Nice skirt with big pockets. My only suggestion would be to add a little spandex to the material blend to give a small degree of stretch.' },
    { date: '2020-01-04', ratingStars: 4 },
    { date: '2020-01-04', ratingStars: 5, name: 'David, Las Vegas', review: 'This is a truly wonderful skirt, very comfortable. I was torn between the khaki and grey, ultimately chose the grey as a I already have a couple of khaki kilts. This will be quite wonderful to wear out when I am practicing my favorite recreational activity of taking pictures.\n\nInitially, I ordered a size smaller than I should have - my mistake. Joe was wonderful and took care of that for me quickly. Thanks sir!' },
    { date: '2020-07-10', ratingStars: 5 },
    { date: '2020-07-10', ratingStars: 4, review: 'quite perfect for a man' },
    { date: '2020-07-10', ratingStars: 5, name: 'Adam in Ohio', review: 'Very well made. I am sure this skirt will last me forever. Looking forward to more designs.' },
    { date: '2020-08-14', ratingStars: 5 },
    { date: '2020-08-14', ratingStars: 5, name: 'Charles', review: 'Thankful some made a skirt for men and doesn’t force men to wear feminine clothes to access skirts.' },
    { date: '2020-09-12', ratingStars: 5 },
    { date: '2020-09-12', ratingStars: 4, review: 'very friendly, good service' },
    { date: '2020-09-23', ratingStars: 5 },
    { date: '2020-12-08', ratingStars: 5 },
    { date: '2021-01-23', ratingStars: 5, name: 'Kristi in Stillwater, MN', review: 'My Unaligned Skirt has become my favorite article of clothing! I have lamented the pathetic pockets in women\'s clothing for as long as I can remember, so having useful pockets has been incredible! The quality of the garment is great and I believe the classic cut will make it a wardrobe staple for me for years to come.' },
    { date: '2021-01-23', ratingStars: 5, name: 'Kevin', review: 'The unaligned skirt is great! It fits well and has pockets. With the cargo pockets I can carry more than pants pockets comfortably, I don\'t have to remove my cellphone out of my back pocket to sit down! This skirt is going to be cooler than my kilt in the summer heat as well.' },
    { date: '2021-02-28', ratingStars: 4, name: 'Jaroslav' },
    { date: '2021-02-28', ratingStars: 2 },
    { date: '2021-03-03', ratingStars: 5, review: 'Lighter and cooler than my kilts. Excellent for warmer weather.' },
    { date: '2021-03-23', ratingStars: 5 },
    { date: '2021-04-24', ratingStars: 5 },
    { date: '2021-05-26', ratingStars: 5, name: 'Ben', review: 'The Unaligned skirt is a great companion to my collection of utilikilts.' },
    { date: '2021-05-27', ratingStars: 5 },
    { date: '2021-05-27', ratingStars: 5, name: 'Mike', review: 'Excellent quality, I can\'t wait to wear it!' },
    { date: '2021-05-27', ratingStars: 4 },
    { date: '2021-06-12', ratingStars: 5, name: 'Mentuhotep, in Illinois', review: 'I finally order my first skirt after a few years of procrastination. My wife said she wants one as well. It is the best edition to my hot summer wardrobe.' },
    { date: '2021-07-26', ratingStars: 5 },
    { date: '2021-07-27', ratingStars: 5, name: 'Stickthelizard' },
    { date: '2021-08-28', ratingStars: 4 },
    { date: '2021-08-29', ratingStars: 4 },
    { date: '2021-08-30', ratingStars: 5 },
    { date: '2021-10-02', ratingStars: 5 },
    { date: '2021-10-02', ratingStars: 5, review: 'These skirts are very well-made and extremely comfortable, among the best I\'ve tried.' },
    { date: '2021-11-06', ratingStars: 5 },
    { date: '2021-11-07', ratingStars: 5, name: 'Shannon A' },
    { date: '2021-12-22', ratingStars: 5, review: 'Great quality product, really comfortable to wear, love the pockets - makes carrying essentials (e.g. phone) easy' },
    { date: '2021-03-09', ratingStars: 5 },
    { date: '2022-03-09', ratingStars: 5, name: 'Daniel', review: 'Worth it' },
    { date: '2022-04-24', ratingStars: 5, name: 'Nick' },
    { date: '2022-05-21', ratingStars: 4 },
    { date: '2022-05-23', ratingStars: 5, review: 'Thanks Joe for contributing to the start of a long overdue revolution in men\'s fashion to make practical and affordable skirts an option for forward thinking men!' },
    { date: '2022-05-24', ratingStars: 4 },
    { date: '2022-05-31', ratingStars: 5 },
    { date: '2022-06-16', ratingStars: 5, review: 'Perfect first skirt for a man!' },
    { date: '2022-07-16', ratingStars: 5, name: 'Ike in LoCo', review: 'Discerning customers won\'t be satisfied, they\'ll be delighted!' },
    { date: '2022-07-16', ratingStars: 5, name: 'Mark' },
    { date: '2022-07-16', ratingStars: 5, review: 'The skirts are of fantastic quality and shipped quickly, I have ordered several already' },
    { date: '2022-08-15', ratingStars: 5 },
    { date: '2022-08-15', ratingStars: 4 },
];
